server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt
security:
  user:
    name: user
    password: 123456
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
